version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: validator-api-swagger
    ports:
      - "80:3000"  # Adjust the ports as per your application's needs
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
