name: Trigger auto deployment for commai-swagger-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/commai-swagger-prod-AutoDeployTrigger-7a452f74-ddab-4336-a8cc-69a450e2cec1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.COMMAISWAGGERPROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COMMAISWAGGERPROD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COMMAISWAGGERPROD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: commaiacrprod.azurecr.io
          registryUsername: ${{ secrets.COMMAISWAGGERPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COMMAISWAGGERPROD_REGISTRY_PASSWORD }}
          containerAppName: commai-swagger-prod
          resourceGroup: commai-rg-Prod
          imageToBuild: commaiacrprod.azurecr.io/commai-swagger-prod:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


